# Generated by Django 5.2 on 2025-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='prev_job_title1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='prev_job_title2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='prev_job_title3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
