# Generated by Django 5.2 on 2025-04-30 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_workexperience_prev_job_title1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
