# Generated by Django 5.2 on 2025-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certificate_obtained_from',
            field=models.CharField(default='', max_length=250),
        ),
    ]
