# Generated by Django 5.2 on 2025-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_certificates_certificate_obtained_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certificate_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
