# Generated by Django 5.2 on 2025-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_certificates_certificate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(default=None, null=True)),
                ('subject1', models.CharField(default='', max_length=100)),
                ('subject2', models.CharField(default='', max_length=100)),
                ('subject3', models.CharField(default='', max_length=100)),
                ('subject4', models.CharField(default='', max_length=100)),
                ('subject5', models.CharField(default='', max_length=100)),
                ('subject6', models.CharField(default='', max_length=100)),
                ('subject7', models.CharField(default='', max_length=100)),
                ('subject8', models.CharField(default='', max_length=100)),
                ('subject9', models.CharField(default='', max_length=100)),
                ('subject10', models.CharField(default='', max_length=100)),
                ('graduated', models.BooleanField(default=False)),
            ],
        ),
    ]
