# Generated by Django 5.2 on 2025-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject10',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject7',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject8',
        ),
        migrations.RemoveField(
            model_name='education',
            name='subject9',
        ),
        migrations.AddField(
            model_name='education',
            name='subjects',
            field=models.TextField(default=''),
        ),
    ]
