# Generated by Django 5.2 on 2025-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_education_subject1_remove_education_subject10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='college',
            field=models.CharField(default='', max_length=500),
        ),
    ]
