# Generated by Django 5.2 on 2025-06-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_education_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
